### PR TITLE
Define TranslatedString#as_json for ActiveSupport compatibility

### LINKED ISSUE #139: ActiveSupport::JSON.encode fails in ruby 2.3.x
##### Description

In Ruby 2.2.4 ActiveSupport::JSON.encode works with R18n::TranslatedString, but in 2.3.2 it fails. This shows up in our Rails app when we are attempting to render an object that contains translated strings to JSON. 

For repro code, please see the repo [here](https://github.com/creddy/r18n-ruby-2-3)

```ruby 
require "r18n-core"
require "active_support"

R18n.default_places = 'translations'
R18n.set('en')

include R18n::Helpers

puts ActiveSupport::JSON.encode(t.foobar)
```

##### Expected 

➜  r18n-ruby-2-3 [2.2.4] (master) ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]
➜  r18n-ruby-2-3 [2.2.4] (master) rake
"foobar translated"

##### Actual

➜  r18n-ruby-2-3 [2.3.2] (master) ruby -v
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]
➜  r18n-ruby-2-3 [2.3.2] (master) rake
rake aborted!
TypeError: can't convert R18n::TranslatedString to Hash (R18n::TranslatedString#to_hash gives R18n::Untranslated)
test.rb:9:in `<top (required)>'

Thank you

### PR DESCRIPTION
**Pull request by timcraft**
Fixes #139 

ActiveSupport defines String#as_json returning `self`, which doesn't work for TranslatedString. Fixing by defining TranslatedString#as_json to return a String.

### CODE REVIEW

File: r18n-core/lib/r18n-core/translated_string.rb [hunk 1]
```diff
@@ -59,6 +59,11 @@ def to_s
       end
     end
 
+    # Define `as_json` for ActiveSupport compatibility.
+    def as_json(options = nil)
+      to_str
```
Comment (AlexWayfer) [inline r18n-core/lib/r18n-core/translated_string.rb]: Why `to_str` and not `to_s`?

Comment (timcraft) [reply r18n-core/lib/r18n-core/translated_string.rb]: Because it definitely returns a String and it's easier to verify/review (given that TranslatedString is a subclass of String and typically only String defines `to_str`). Using `to_s` will probably work too with the current implementation, but historically `to_s` wasn't guaranteed to return a String, and it's more complex to verify/review its behaviour.

Comment (AlexWayfer) [reply r18n-core/lib/r18n-core/translated_string.rb]: Please, pay attention, there is redefined `TranslatedString#to_s` method and no `#to_str`.

Maybe you should use `#to_s`, maybe change redefining `#to_s` to `#to_str`.

Comment (timcraft) [reply r18n-core/lib/r18n-core/translated_string.rb]: TranslatedString subclasses String, which defines the `to_str` method:

http://ruby-doc.org/core-2.4.2/String.html#method-i-to_str

Comment (AlexWayfer) [reply r18n-core/lib/r18n-core/translated_string.rb]: I know, but `#to_s` has `html_safe`, with which the result can be better.

Comment (timcraft) [reply r18n-core/lib/r18n-core/translated_string.rb]: A string doesn't need to be marked as html_safe if it's going to be encoding as JSON, ActiveSupport::JSON handles escaping using its own EscapedString class.

Comment (ai) [reply r18n-core/lib/r18n-core/translated_string.rb]: In `_dump` we use `to_str` method too.

It is good question, do we need `html_safe` in `to_json`.

Anyway, I grant decision to @timcraft :)

Comment (AlexWayfer) [reply r18n-core/lib/r18n-core/translated_string.rb]: >A string doesn't need to be marked as html_safe if it's going to be encoding as JSON, ActiveSupport::JSON handles escaping using its own EscapedString class.

OK.

I was also confused by the difference between `as_json` and `to_json`, and projects without ActiveSupport and with system gem `json`, but it's `r18n-rails`, so OK.

Comment (ai) [reply r18n-core/lib/r18n-core/translated_string.rb]: “as_json and to_json” is a good question

Comment (AlexWayfer) [reply r18n-core/lib/r18n-core/translated_string.rb]: Don't misunderstood me, please: I'm not against changes, I'm looking for the best way for everyone :hugs:

Comment (AlexWayfer) [reply r18n-core/lib/r18n-core/translated_string.rb]: Oh, no, this is not `r18n-rails`, this is `r18n-core`. Let's be more careful and think about these changes, also for "projects without ActiveSupport"-compatibility.

Comment (AlexWayfer) [reply r18n-core/lib/r18n-core/translated_string.rb]:
```ruby
> RUBY_VERSION
=> "2.4.2"

> JSON::VERSION
=> "2.0.4"

> 'foo bar'.to_json
=> "\"foo bar\""

> 'foo bar'.as_json
NoMethodError: undefined method `as_json' for "foo bar":String
```

Comment (AlexWayfer) [reply r18n-core/lib/r18n-core/translated_string.rb]: I guess that `#as_json` is for ActiveModels, and here we should use `#to_json` with `#to_s` (for `html_safe`.

Comment (timcraft) [reply r18n-core/lib/r18n-core/translated_string.rb]: @ai Yes, and `to_str` could also be used instead of `String.new(super)` in the `to_s` method.

@AlexWayfer The as_json method comes from ActiveSupport, and it's compatibility with ActiveSupport that the PR is addressing. If you look at the source of ActiveSupport you can see how it works: to_json calls ActiveSupport::JSON.encode which calls as_json.

Comment (ai) [reply r18n-core/lib/r18n-core/translated_string.rb]: @timcraft sure. Are we ready to accept this PR? Or you want to replace `String.new(super)`?

Comment (AlexWayfer) [reply r18n-core/lib/r18n-core/translated_string.rb]: @timcraft ActiveSupport-specific realization should be in `r18n-rails`, not in `r18-core`, please.

Comment (ai) [reply r18n-core/lib/r18n-core/translated_string.rb]: @AlexWayfer We have `html_safe` things here. The only thing that R18n Core should work without Rails.

Comment (AlexWayfer) [reply r18n-core/lib/r18n-core/translated_string.rb]: > The only thing that R18n Core should work without Rails.

OK. Maybe it'll work for Rails and not-Rails with `#to_json` instead of `#as_json`, but I'm not sure.

**Comment by ai** [comment]
Released in 2.2.
